### ISSUE TITLE
Build error : 'Auth0.plist file is not found'

### ISSUE THREAD

**Issue by rizwan95** [auth0-samples/auth0-ios-swift-siwa-samples#2]
Looks like 'Auth0.plist' isn't included in the project and hence the project fails to build.

**Comment by rizwan95** [comment]
I have fixed the issue and submitted a PR here : https://github.com/auth0-samples/auth0-ios-swift-siwa-samples/pull/3

**Comment by stevehobbsdev** [comment]
@rizwan95 Thanks! Left a comment on the PR for you :)
